### ISSUE TITLE
V5 Help

### ISSUE THREAD

**Issue by burf2000** [sealj553/VexV5Doom#1]
Hi there, first wow for porting Doom to V5, that's pretty epic.  I have not started coding for V5 yet but have done the old EDR/IQ etc with ROS, iOS Android etc.

Have you managed to communicate between the V5 and say a Raspberry Pi/PC?Mobile device?  If so how did you do it.

Also what programming language would you recommend for the V5?  I used RobotC previously

**Comment by sealj553** [comment]
Hi, thanks for the interest. This project doesn't do any communication, but the code for my VEX U robot does.
This is the robot project: https://github.com/UMLRoboticsClub/VexTurningPoint2019_Swift
It has a quick getting started guide in the readme that you might find helpful.
And this runs on a computer or Raspberry Pi: https://github.com/UMLRoboticsClub/VexTurningPoint2019_Vision
The goal is an auto-targeting shooter robot for the Turning Point challenge. Right now, it sends the location of a vision target on camera to the V5 which displays a rectangle on screen.

For programming, I would go with PROS: https://pros.cs.purdue.edu/, docs here: https://pros.cs.purdue.edu/v5/index.html. It's standard C or C++ and uses LVGL for graphics.

When you plug in the V5 via USB, it creates 2 serial ports. One for user communication and one for sending programs. PROS uses stdin and stdout for serial communications on the user port, so it's pretty simple. You can use stuff like printf/scanf/getline, etc. On the computer side, you just need a way to send and receive data over serial.

Also, if you want to parse the data from the V5 running PROS, it's much easier if you call `serctl(SERCTL_DISABLE_COBS, NULL);` to disable COBS (https://en.wikipedia.org/wiki/Consistent_Overhead_Byte_Stuffing).

**Comment by burf2000** [comment]
Thank you for taking the time to reply with such an epic example.  I have done a few things with EDR and Ros, IQ and iOS etc.  I always try to make videos and share the code, its nice like yourself to help others.  How did you find the camera, is the processing done on the PI?

**Comment by sealj553** [comment]
I'm using a Logitech C930e because it's 1080p and has a large field of view. It's plugged in to the PI which then detects targets and sends the coordinates to the V5. Then the robot will align itself to the target and fire.
