### ISSUE TITLE
Not working on version 1.0.7

### ISSUE THREAD

**Issue by Uriel1795** [sealj553/VexV5Doom#2]
Thanks for bringing DOOM to the V5, you have my honest respect. However, I cannot get it to work on my V5. The screen just stays black and nothing really happens.

 I am running version 1.0.7, I am not sure if it is because of the update or if I am missing anything.

If I am missing anything, please advice me. Otherwise, please guide me into what should be done.

Thanks a lot for your hard work. I expect your response.

**Comment by sealj553** [comment]
Hi, thanks for the kind words. I don't have a V5 with me at the moment to test the newer version, but you can connect with a serial terminal to see the debug output from the V5. It's possible the program can't read from the microSD card or something similar.

In case you don't know, the V5 creates 2 serial interfaces: one for programming and one for serial IO. IIRC it's the second one `/dev/ttyUSB1` on linux or `COM1` on windows. You'd need to connect at 115200 baud. When you start V5Doom, it'll probably say "Starting DOOM..." then some error message.

**Comment by sealj553** [comment]
I just updated PROS to the latest version and I'm running firmware 1.0.7 as well. Still working for me. So it sounds like an SD card problem.
